version: '3.7'

services:
  modx:
    build:
      context: ./docker
      dockerfile: Dockerfile
    #volumes:
      #- ./src:/var/www/html/modx
    depends_on:
      - mysql
    ports:
      - 80:80
    tty: true
    restart: always

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: modx
